# Generated by Django 5.1 on 2025-04-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('mechanic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('car_license_number', models.CharField(max_length=20)),
                ('car_engine_number', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('mechanic', models.ForeignKey(db_column='mechanic_id', on_delete=django.db.models.deletion.CASCADE, to='car_workshop.mechanic')),
            ],
        ),
    ]
