# Generated by Django 5.1 on 2025-04-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
